#
# Copyright (c) Siemens AG 2022 ALL RIGHTS RESERVED
#
# Asset link Dummy Driver for Industrial Asset Hub
# Depends on Industrial Asset Hub gateway

services:
  dummy-driver:
    restart: always
    image: 'ghcr.io/industrial-asset-hub/iah/dummy-driver:0.0.3-rc.18.2051ceb0-204918630'
    networks:
      - 01-cdm
    mem_limit: 300mb
    volumes:
      - ./cfg-data:/shared-cfg/
    command:
      - '-grpc-server-endpoint-address=dummy-driver'
      - '-grpc-server-address=0.0.0.0:8082'
      - '-grpc-registry-address=grpc-server-registry:50051'

networks:
  01-cdm:
    name: cdm
    external: true
